namespace Apps.Apertera.Constants;

public static class LanguageConstants
{
    public static readonly Dictionary<string, string> Languages = new()
    {
        { "afr", "Afrikaans" },
        { "ara", "Arabic" },
        { "arm", "Armenian" },
        { "aze", "Azerbaijani" },
        { "baq", "Basque" },
        { "bel", "Belarusian" },
        { "ben", "Bengali" },
        { "bos", "Bosnian" },
        { "bul", "Bulgarian" },
        { "cat", "Catalan" },
        { "chi", "Chinese (Simplified)" },
        { "hrv", "Croatian" },
        { "cze", "Czech" },
        { "dan", "Danish" },
        { "dut", "Dutch" },
        { "eng", "English" },
        { "est", "Estonian" },
        { "fin", "Finnish" },
        { "fra", "French" },
        { "geo", "Georgian" },
        { "ger", "German" },
        { "gre", "Greek" },
        { "guj", "Gujarati" },
        { "heb", "Hebrew" },
        { "hin", "Hindi" },
        { "hun", "Hungarian" },
        { "ice", "Icelandic" },
        { "ind", "Indonesian" },
        { "gle", "Irish" },
        { "ita", "Italian" },
        { "jpn", "Japanese" },
        { "kan", "Kannada" },
        { "kaz", "Kazakh" },
        { "kor", "Korean" },
        { "lav", "Latvian" },
        { "lit", "Lithuanian" },
        { "mac", "Macedonian" },
        { "may", "Malay" },
        { "mal", "Malayalam" },
        { "mlt", "Maltese" },
        { "mar", "Marathi" },
        { "nep", "Nepali" },
        { "nor", "Norwegian" },
        { "per", "Persian" },
        { "pol", "Polish" },
        { "por", "Portuguese" },
        { "pan", "Punjabi" },
        { "rum", "Romanian" },
        { "rus", "Russian" },
        { "scc", "Serbian" },
        { "slo", "Slovak" },
        { "slv", "Slovenian" },
        { "spa", "Spanish" },
        { "swa", "Swahili" },
        { "swe", "Swedish" },
        { "tgl", "Tagalog" },
        { "tam", "Tamil" },
        { "tel", "Telugu" },
        { "tha", "Thai" },
        { "tur", "Turkish" },
        { "ukr", "Ukrainian" },
        { "urd", "Urdu" },
        { "vie", "Vietnamese" },
        { "wel", "Welsh" },
    };
}
